#! /usr/bin/env bash
set -e

export DIGITALBITS_HOME="/opt/digitalbits"
export PGHOME="$DIGITALBITS_HOME/postgresql"
export SUPHOME="$DIGITALBITS_HOME/supervisor"
export COREHOME="$DIGITALBITS_HOME/core"
export HZHOME="$DIGITALBITS_HOME/frontier"

export PGBIN="/usr/lib/postgresql/9.5/bin"
export PGDATA="$PGHOME/data"
export PGUSER="digitalbits"
export PGPORT=5432

QUICKSTART_INITIALIZED=false
CURRENT_POSTGRES_PID=""

function main() {
	echo ""
	echo "Starting DigitalBits Quickstart"
	echo ""

	process_args $*

	echo "mode: $DIGITALBITS_MODE"
	echo "network: $NETWORK ($NETWORK_PASSPHRASE)"

	copy_defaults
	init_db
	init_digitalbits_core
	init_frontier
	copy_pgpass
	stop_postgres  # this gets started in init_db
	# launch services
	exec_supervisor
}

function process_args() {
	while [[ -n "$1" ]]; do
  	ARG="$1"
	  shift


	  case "${ARG}" in
	  --testnet)
	    NETWORK="testnet"
	    ;;
	  --pubnet)
	    NETWORK="pubnet"
	    ;;
	  *)
	    echo "Unknown container arg $ARG" >&2
	    exit 1
	  esac
	done

	# TODO: ask for what network to use
	if [ -z "$NETWORK" ]; then
		NETWORK="testnet"
	fi

	case "$NETWORK" in
	testnet)
    export NETWORK_PASSPHRASE="TestNet Global DigitalBits Network ; December 2020"
    ;;
	pubnet)
    export NETWORK_PASSPHRASE="LiveNet Global DigitalBits Network ; February 2021"
    ;;
	*)
		echo "Unknown network: '$NETWORK'" >&2
		exit 1
	esac

	# Are we ephemeral or persistent?
	if [ -z "$DIGITALBITS_MODE" ]; then
		if [ -f "/opt/digitalbits/.docker-ephemeral" ]; then
			DIGITALBITS_MODE="ephemeral"
		else
			DIGITALBITS_MODE="persistent"
		fi
	fi
}

function set_pg_password() {

	if [ -n "$POSTGRES_PASSWORD" ]; then
		PGPASS=$POSTGRES_PASSWORD
		echo "using POSTGRES_PASSWORD"
		return 0
	fi

	# use a random password when ephemeral (or some other unknown mode)
	if [ "$DIGITALBITS_MODE" != "persistent" ]; then
		PGPASS=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' |  head -c 16)
		echo "postgres password: $PGPASS"
		return 0
	fi

	if [ -n "$PGPASS" ]; then
		echo "postgres password: $PGPASS"
		return 0
	fi

	# ask for a password when persistent
	read -s -p "Enter New Postgresql Password: " PGPASS
	echo ""
	read -s -p "Confirm: " PGPASS_CONFIRMATION
	echo ""

	if [ -z "$PGPASS" ]; then
		echo "Password empty" >&2
		exit 1
	fi

	if [ "$PGPASS" != "$PGPASS_CONFIRMATION" ]; then
		echo "Password mistmach" >&2
		exit 1
	fi

}

function copy_defaults() {
	local CP="rsync -a"

	if [ -d $PGHOME/etc ]; then
		echo "postgres: config directory exists, skipping copy"
	else
		$CP /opt/digitalbits-default/common/postgresql/ $PGHOME
	fi

	if [ -d $SUPHOME/etc ]; then
		echo "supervisor: config directory exists, skipping copy"
	else
		$CP /opt/digitalbits-default/common/supervisor/ $SUPHOME
	fi

	if [ -d $COREHOME/etc ]; then
		echo "digitalbits-core: config directory exists, skipping copy"
	else
		$CP /opt/digitalbits-default/common/core/ $COREHOME
		$CP /opt/digitalbits-default/$NETWORK/core/ $COREHOME
	fi

	if [ -d $HZHOME/etc ]; then
		echo "frontier: config directory exists, skipping copy"
	else
		$CP /opt/digitalbits-default/common/frontier/ $HZHOME
	fi
}

function copy_pgpass() {
	local CP="rsync -a"

	$CP /opt/digitalbits/postgresql/.pgpass /root/
	chmod 0600 /root/.pgpass

	$CP /opt/digitalbits/postgresql/.pgpass /home/digitalbits
	chmod 0600 /home/digitalbits/.pgpass
	chown digitalbits:digitalbits /home/digitalbits/.pgpass
}

function init_db() {
	if [ -f $PGHOME/.quickstart-initialized ]; then
		echo "postgres: already initialized"
		return 0
	fi
	pushd $PGHOME

	# workaround!!!! from: https://github.com/nimiq/docker-postgresql93/issues/2
	mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private
	# end workaround

	echo "postgres user: $PGUSER"

	set_pg_password

	run_silent "finalize-pgpass" sed -ri "s/__PGPASS__/$PGPASS/g" /opt/digitalbits/postgresql/.pgpass

	mkdir -p $PGDATA
	chown postgres:postgres $PGDATA
	chmod 0700 $PGDATA

	run_silent "init-postgres" sudo -u postgres $PGBIN/initdb -D $PGDATA

	start_postgres
	run_silent "create-frontier-db" sudo -u postgres createdb frontier
	run_silent "create-core-db" sudo -u postgres createdb core
	run_silent "digitalbits-postgres-user" sudo -u postgres psql <<-SQL
		CREATE USER $PGUSER WITH PASSWORD '$PGPASS';
		GRANT ALL PRIVILEGES ON DATABASE frontier to $PGUSER;
		GRANT ALL PRIVILEGES ON DATABASE core to $PGUSER;
	SQL

	touch .quickstart-initialized
	popd
}

function init_digitalbits_core() {
	if [ -f $COREHOME/.quickstart-initialized ]; then
		echo "core: already initialized"
		return 0
	fi
	pushd $COREHOME

	run_silent "chown-core" chown digitalbits:digitalbits .
	run_silent "chown-history" chown digitalbits:digitalbits /opt/digitalbits/history-cache
	run_silent "finalize-core-config" sed -ri "s/__PGPASS__/$PGPASS/g" etc/digitalbits-core.cfg

	start_postgres
	run_silent "init-core-db" sudo -u digitalbits digitalbits-core --conf etc/digitalbits-core.cfg new-db
	run_silent "init-core-hist" sudo -u digitalbits digitalbits-core --conf etc/digitalbits-core.cfg new-hist cache

	touch .quickstart-initialized
	popd
}

function init_frontier() {
	if [ -f $HZHOME/.quickstart-initialized ]; then
		echo "frontier: already initialized"
		return 0
	fi
	pushd $HZHOME

	run_silent "chown-frontier" chown digitalbits:digitalbits .
	
	sed -ri \
		-e "s/__PGPASS__/$PGPASS/g" \
		-e "s/__NETWORK__/$NETWORK_PASSPHRASE/g" \
		etc/frontier.env

	start_postgres
	run_silent "init-frontier-db" sudo -u digitalbits ./bin/frontier db init

	touch .quickstart-initialized
	popd
}

function exec_supervisor() {
	echo "starting supervisor"
	exec supervisord -n -c $SUPHOME/etc/supervisord.conf
}

# run_silent is a utility function that runs a command with an abbreviated
# output provided it succeeds.
function run_silent() {
	local LABEL=$1
	shift
	local COMMAND=$1
	shift
	local ARGS=$@
	local OUTFILE="/tmp/run_silent.out"

	echo -n "$LABEL: "
	set +e

	$COMMAND $ARGS &> $OUTFILE

	if [ $? -eq 0 ]; then
    echo "ok"
	else
	  echo "failed!"
		echo ""
		cat $OUTFILE
		exit 1
	fi

	set -e
}

function start_postgres() {
	if [ ! -z "$CURRENT_POSTGRES_PID" ]; then
		return 0
	fi

	sudo -u postgres $PGBIN/postgres -D $PGDATA -c config_file=$PGHOME/etc/postgresql.conf &> /dev/null &
	CURRENT_POSTGRES_PID=$!

	while ! sudo -u postgres psql -c 'select 1' &> /dev/null ; do
	  echo "Waiting for postgres to be available..."
	  sleep 1
	done

	echo "postgres: up"
}

function stop_postgres() {
	if [ -z "$CURRENT_POSTGRES_PID" ]; then
		return 0
	fi

	killall postgres
	# wait for postgres to die
	while kill -0 "$CURRENT_POSTGRES_PID" &> /dev/null; do
		sleep 0.5
	done
	echo "postgres: down"
}

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

main $@
